project:
  type: book
  output-dir: docs

book:
  repo-url: https://github.com/PMassicotte/r-spatial-cookbook
  repo-actions: [issue]
  title: "R Spatial Cookbook"
  author: "Philippe Massicotte"
  date: today
  chapters:
    - index.qmd
    - chapters/modis.qmd
    - chapters/hdf4.qmd
    - chapters/nsidc.qmd
    - chapters/he5.qmd
    - chapters/vsicurl.qmd
    - chapters/filtering.qmd
    - chapters/references.qmd

format:
  html:
    fig-format: png
    fig-dpi: 300
    fig-align: center
    highlight-style: a11y
    df-print: kable
    toc-depth: 4
    toc-expand: 4
    theme:
      - cosmo
      - brand

execute:
  warning: false
  message: false
  freeze: auto
