project:
  type: book
  output-dir: docs

book:
  repo-url: https://github.com/PMassicotte/r-spatial-cookbook
  repo-actions: [issue]
  title: "R Spatial Cookbook"
  author: "Philippe Massicotte"
  date: today
  chapters:
    - index.qmd
    - part: "Importing and Exporting Data"
      chapters:
        - chapters/importing/01_binary_format.qmd
        - chapters/importing/02_hdf4.qmd
        - chapters/importing/03_he5.qmd
        - chapters/importing/04_modis.qmd
        - chapters/importing/05_vsicurl.qmd
    - part: "Filtering"
      chapters:
        - chapters/filtering/01_filtering.qmd
    - chapters/references.qmd

format:
  html:
    fig-format: png
    fig-dpi: 300
    fig-align: center
    highlight-style: a11y
    df-print: kable
    toc: true
    toc-depth: 4
    toc-expand: 4
    theme:
      - cosmo
      - brand

execute:
  warning: false
  message: false
  freeze: auto

knitr:
  opts_chunk:
    dev: ragg_png
